import os
import xlsxwriter
from fpdf import FPDF
from datetime import datetime
from utils.settings_manager import SettingsManager


class ExportUtils:
    """
    الكلاس الأساسي المسؤول عن:
    - تصدير Excel
    - تصدير PDF
    - فتح PDF للطباعة (Print Preview)
    """

    # ===============================================================
    # EXPORT TO EXCEL
    # ===============================================================
    @staticmethod
    def export_excel(filename, headers, rows):
        wb = xlsxwriter.Workbook(filename)
        ws = wb.add_worksheet("Report")

        bold = wb.add_format({"bold": True, "bg_color": "#DDEBF7", "border": 1})
        cell = wb.add_format({"border": 1})

        # كتابة رؤوس الأعمدة
        for col, header in enumerate(headers):
            ws.write(0, col, header, bold)

        # كتابة البيانات
        for r, row in enumerate(rows, start=1):
            for c, value in enumerate(row):
                ws.write(r, c, value, cell)

        wb.close()
        return True

    # ===============================================================
    # EXPORT TO PDF
    # ===============================================================
    @staticmethod
    def export_pdf(filename, title, headers, rows):
        settings = SettingsManager().load_settings()

        company = settings.get("company_name", "Company Name")
        phone = settings.get("company_phone", "01000551634")
        email = settings.get("company_email", "info@example.com")
        logo = settings.get("logo_path", "")

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=10)
        pdf.add_page()

        # --- HEADER ---
        if logo and os.path.exists(logo):
            pdf.image(logo, x=10, y=8, w=25)

        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, company, ln=1, align="R")

        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 6, f"Phone: {phone}", ln=1, align="R")
        pdf.cell(0, 6, f"Email: {email}", ln=1, align="R")

        pdf.ln(10)

        # --- TITLE ---
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, title, ln=1, align="C")

        pdf.ln(5)

        # --- TABLE HEADER ---
        pdf.set_font("Arial", "B", 11)
        for h in headers:
            pdf.cell(40, 10, str(h), border=1, align="C")
        pdf.ln()

        # --- TABLE DATA ---
        pdf.set_font("Arial", "", 10)
        for row in rows:
            for value in row:
                pdf.cell(40, 8, str(value), border=1, align="C")
            pdf.ln()

        pdf.ln(10)
        pdf.set_font("Arial", "I", 9)
        pdf.cell(
            0,
            8,
            "Generated by Inventory Pro — All Rights Reserved",
            ln=1,
            align="C"
        )

        pdf.output(filename)
        return True

    # ===============================================================
    # PRINT PDF DIRECTLY
    # ===============================================================
    @staticmethod
    def export_and_open_pdf(title, headers, rows):
        """Generate temporary PDF and open it."""
        filename = f"temp_report_{datetime.now().timestamp()}.pdf"
        ExportUtils.export_pdf(filename, title, headers, rows)

        try:
            os.startfile(filename)  # Windows Print Preview
        except:
            pass

        return True


# =======================================================================
#   🔥 BACKWARD COMPATIBILITY LAYER 🔥
# =======================================================================
# صفحات قديمة لسه بتستورد:
# from utils.export_utils import Exporter
# فنعمل Alias يحافظ على التوافق
class Exporter(ExportUtils):
    """Backward compatible class name."""
    pass
